title: "Манифест DTA\\18.26 | Суверенная Цифровая Этика"
description: "Официальный сайт Метода DTA\\18.26. Инженерные и этические стандарты защиты человеческого капитала от алгоритмического выгорания и коммерческих дофаминовых ловушек Big Tech."
keywords: "DTA 18.26, AI Alignment, суверенная цифровая этика, защита префронтальной коры, экономика внимания, выравнивание искусственного интеллекта, семантическое вето"
theme: jekyll-theme-cayman
